### ISSUE TITLE
add new rules

### ISSUE THREAD

**Issue by pentest30** [kiegroup/optaplanner-training#6]
i want to add new rule to the curriculum course solver (assign certain courses to certain rooms ).
i write this rule :rule 
"roomToCourse"
    when $room :Room($roomType :roomType) $course : Course(getCourseType() != $roomType  )
    then scoreHolder.addHardConstraintMatch(kcontext, -10);
end
 but optaplanner does not take it in considiration !!

**Comment by ge0ffrey** [comment]
Please use
https://www.optaplanner.org/community/forum.html
